import { GithubIcon, InstagramIcon, LinkedinIcon } from "./lib/all_icons";
import { EventDataType } from "./types/EventData";
import { NavLinkType } from "./types/Navlink";
import { NewEventFormFieldsType } from "./types/NewEventFormField";
import { SearchFilterDataType } from "./types/SearchFilterData";
import { SocialHandleDataType } from "./types/SocialHandleData";

const NavLinksData: NavLinkType[] = [
  {
    href: "/new-event",
    text: "Create New Event",
    linkType: "link",
  },
  {
    href: "/",
    text: "Explore All Events",
    linkType: "link",
  },
];

const SocialHandleData: SocialHandleDataType[] = [
  {
    name: "Github",
    icon: GithubIcon,
    link: "https://github.com/Prashant-S29/",
  },
  {
    name: "Linkedin",
    icon: LinkedinIcon,
    link: "https://www.linkedin.com/in/prashant-singh-529391250/",
  },
  {
    name: "Instagram",
    icon: InstagramIcon,
    link: "https://www.instagram.com/web_with_prashant",
  },
];

const EventData: EventDataType[] = [
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
  {
    eventName: "Frontend Intern",
    eventCompanyName: "Proelevate",
    // eventCompanyLogo: eventCompanyLogo,
    eventDescription: "A questionnaire for frontend interns by Arsh Goyal",
    eventDate: "2023-04-01",
    eventTime: "10:00 AM",
    eventLocation: "Online",
    eventLink: "https://arshgoyal.github.io/Frontend-Intern-Questionnaire/",
  },
];

const SearchFilerData: SearchFilterDataType[] = [
  {
    category: "Event Type",
    filters: [
      "Party",
      "Meetup",
      "Conference",
      "Workshop",
      "Hackathon",
      "Open Source",
      "Other",
    ],
  },
  {
    category: "Event Domain",
    filters: [
      "Programming",
      "Design",
      "UX",
      "UI",
      "Data Science",
      "Machine Learning",
      "Other",
    ],
  },
  {
    category: "Event Mode",
    filters: ["Virtual", "In-Person"],
  },
];

const NewEventFormFileds: NewEventFormFieldsType[] = [
  {
    fieldName: "eventName",
    fieldType: "text",
    placeholder: "Event Name",
    isRequired: true,
  },
  {
    fieldName: "eventCompanyName",
    fieldType: "text",
    placeholder: "Company Name",
    isRequired: true,
  },
  {
    fieldName: "eventDescription",
    fieldType: "textarea",
    placeholder: "Description",
    isRequired: true,
  },
  {
    fieldName: "eventDate",
    fieldType: "date",
    placeholder: "Event Date - eg: 29th May, 2023",
    isRequired: true,
  },
  {
    fieldName: "eventTime",
    fieldType: "time",
    placeholder: "Event Time - eg: 10:00 AM - 11:00 PM",
    isRequired: true,
  },
  {
    fieldName: "eventLocation",
    fieldType: "text",
    placeholder: "Event Location",
    isRequired: true,
  },
  {
    fieldName: "eventLink",
    fieldType: "text",
    placeholder: "Event Link",
    isRequired: true,
  },
];

export {
  NavLinksData,
  SocialHandleData,
  EventData,
  SearchFilerData,
  NewEventFormFileds,
};
